Add support for Python3 dependencies with rosdep tags. Simplifies ins…
Liquid-ai/Plankton pull request #21
Opened 2020-10-27 16:05 UTC by tdenewiler

…talling dependencies on Noetic.

Signed-off-by: Thomas Denewiler <thomas.denewiler@navy.mil>

2020-10-27 19:57 UTC, tdenewiler commented
This change also helps on Ubuntu 20.04 with ROS2 Foxy.

2020-10-28 17:25 UTC, jpliquid requested changes
Hi @tdenewiler!
Thank you for pointing out that incorrect dependency. Plankton does not support Noetic and Python 2.7, so testing the version is not required. I suggested the following changes. Could you update your commit please ?

2020-10-28 17:25 UTC, jpliquid commented on uuv_control/uuv_control_utils/package.xml
> +  <exec_depend condition="$ROS_PYTHON_VERSION == 2">python-yaml</exec_depend>
```suggestion
```

2020-10-28 17:25 UTC, jpliquid commented on uuv_control/uuv_control_utils/package.xml
> +  <exec_depend condition="$ROS_PYTHON_VERSION == 3">python3-yaml</exec_depend>
```suggestion
  <exec_depend>python3-yaml</exec_depend>
```

2020-10-30 00:04 UTC, jpliquid approved these changes

2020-10-30 00:08 UTC, jpliquid commented
Thanks for your contribution. I needed to change the title of the PR to reflect its content before merging.

2020-10-30 00:09 UTC, merged